[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start -- -p $PORT"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1" 